name: example
description: Example app for testing and demonstrating your Flutter package.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flavor_cli:
    path: ../

flutter:
  assets:
    - .env.dev
    - .env.stage
    - .env.prod
  uses-material-design: true
