// flavor_cli: added

/// Utility class for .env file operations.
class EnvUtils {
  /// Converts camelCase to UPPER_SNAKE_CASE.
  /// e.g. baseUrl -> BASE_URL, debugMode -> DEBUG_MODE
  static String toSnakeCase(String camelCase) {
    return camelCase
        .replaceAllMapped(RegExp(r'([A-Z])'), (m) => '_${m.group(0)}')
        .toUpperCase()
        .replaceAll(RegExp(r'^_'), '');
  }

  /// Converts UPPER_SNAKE_CASE to camelCase.
  /// e.g. BASE_URL -> baseUrl, DEBUG_MODE -> debugMode
  static String fromSnakeCase(String snakeCase) {
    final parts = snakeCase.toLowerCase().split('_');
    if (parts.isEmpty) return snakeCase.toLowerCase();
    return parts.first +
        parts
            .skip(1)
            .map((p) => p.isEmpty ? '' : p[0].toUpperCase() + p.substring(1))
            .join('');
  }

  /// Parses .env file content into a Map<String, String>.
  /// Handles:
  ///   - Comments (lines starting with #)
  ///   - Empty lines
  ///   - Quoted values (single or double)
  ///   - KEY=VALUE format
  static Map<String, String> parseEnvFile(String content) {
    final result = <String, String>{};
    for (final line in content.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final eqIdx = trimmed.indexOf('=');
      if (eqIdx <= 0) continue;
      final key = trimmed.substring(0, eqIdx).trim();
      var value = trimmed.substring(eqIdx + 1).trim();
      // Strip surrounding quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.substring(1, value.length - 1);
      }
      if (key.isNotEmpty) {
        result[key] = value;
      }
    }
    return result;
  }

  /// Generates .env file content from flavor values and field type definitions.
  /// Keys are UPPER_SNAKE_CASE; values are properly escaped.
  static String generateEnvContent(
      Map<String, dynamic> values, Map<String, String> fields) {
    final buffer = StringBuffer();
    buffer.writeln('# Generated by flavor_cli — DO NOT COMMIT');
    for (final entry in fields.entries) {
      final key = toSnakeCase(entry.key);
      final rawValue = values[entry.key];
      final value = _valueToString(rawValue, entry.value);
      buffer.writeln('$key=${escapeEnvValue(value)}');
    }
    return buffer.toString();
  }

  /// Converts a typed value to its string representation for .env files.
  static String _valueToString(dynamic value, String type) {
    if (value == null) return '';
    if (value is bool) return value.toString();
    if (value is num) return value.toString();
    return value.toString();
  }

  /// Escapes a value for use in a .env file.
  /// Wraps in double quotes if value contains spaces, #, =, or newlines.
  static String escapeEnvValue(String value) {
    if (value.isEmpty) return value;
    if (value.contains(' ') ||
        value.contains('#') ||
        value.contains('=') ||
        value.contains('\n') ||
        value.contains('"')) {
      final escaped = value.replaceAll('"', '\\"');
      return '"$escaped"';
    }
    return value;
  }

  /// Infers Dart type from a raw string value.
  /// Returns 'bool', 'int', 'double', or 'String'.
  static String inferType(String value) {
    if (value == 'true' || value == 'false') return 'bool';
    if (int.tryParse(value) != null) return 'int';
    if (double.tryParse(value) != null) return 'double';
    return 'String';
  }
}
